### PR TITLE
Adding PYTHONPATH config to profile.d, environment, later buildpacks

### LINKED ISSUE #24: "ImportError: No module named 'botocore'" but python3-botocore is installed
I have `awscli` in the Aptfile, which depends on botocore.

The install returns:
```
-----> Installing python3-botocore_0.29.0+repack-2_all.deb
```

but later steps (which use the `aws` command) fail with:
```
remote: Traceback (most recent call last):
remote:   File "/tmp/build/.apt/usr/bin/aws", line 15, in <module>
remote:     import awscli.clidriver
remote:   File "/tmp/build/.apt/usr/share/awscli/awscli/clidriver.py", line 16, in <module>
remote:     import botocore.session
remote: ImportError: No module named 'botocore'
```

### PR DESCRIPTION
**Pull request by temujin9**
Fixes #24

### CODE REVIEW

**Comment by temujin9** [comment]
(Sorry about the churn on this. It should be stable, now.)

**Comment by temujin9** [comment]
Excuse me, but why did you close this?

**Comment by ddollar** [comment]
Deprecating the buildpack as I no longer use Heroku. Sorry! Please feel free to fork and take it over!

**Comment by temujin9** [comment]
I have a fork, but it lacks the pull requests, etc. Would you mind transferring ownership of this, so I can resurrect the PRs and issues?

**Comment by ddollar** [comment]
I tried but it conflicted with the fork you already have. Please rename your existing fork and let me know.

**Comment by temujin9** [comment]
Okay, will do.

**Comment by temujin9** [comment]
Done.

**Comment by temujin9** [comment]
Can you try transferring again? I've renamed my fork, but I may have to delete it entirely, and I'd like to know if so.

**Comment by temujin9** [comment]
I have renamed my fork back to its original name, as it appears unlikely that you will try the transfer in a timely manner. Please let me know if / when you are willing to try again, and I will remove my fork (as I expect it is still blocking the transfer even when renamed).

**Pull request closed without merging**
